# requires following ENV vars to be registered in CircleCI :
#
# DOCKER_HUB_USERNAME
# DOCKER_HUB_PASSWORD
#
version: 2

defaults: &defaults
  environment:
    DOCKER_IMAGE_NAME: apigeeks/nexus3-keycloak-plugin
    
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

jobs:
  deploy:
    <<: *defaults
    steps:    
      - checkout        

      - setup_remote_docker

      - run: 
          name: build and push docker image
          command: |
            if [[ -z "$CIRCLE_BUILD_NUM" ]]; then                            
              sudo docker build -t $DOCKER_IMAGE_NAME:latest .
              sudo docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$CIRCLE_TAG
              sudo docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD

              sudo docker push $DOCKER_IMAGE_NAME:$CIRCLE_TAG
              sudo docker push $DOCKER_IMAGE_NAME:latest
            else
              docker build -t $DOCKER_IMAGE_NAME:latest .
              docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$CIRCLE_TAG
              docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD

              docker push $DOCKER_IMAGE_NAME:$CIRCLE_TAG
              docker push $DOCKER_IMAGE_NAME:latest
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
